### ISSUE TITLE
Rain, Togglable via Button

### ISSUE THREAD

**Issue by R0TX** [RotX18/ARProject#2]
## Objective: Add a rain system that can be toggled using an on-screen button

Rain can be toggled using a button

### Tasks:
- [x] Create GameManager.cs to handle button input and toggling of rain
- [x] Source for rain asset from the asset store
- [x] Implement feature by using GameManager.cs to toggle rain 
- [x] Implement 3rd rain mode "Stormy"
- [x] Change button to use icons instead of text

**Comment by R0TX** [comment]
# Started implementation

## Imported RainMaker asset from the asset store
https://assetstore.unity.com/packages/vfx/particles/environment/rain-maker-2d-and-3d-rain-particle-system-for-unity-34938#description
![image](https://user-images.githubusercontent.com/84174550/173160087-98fb0268-128c-41ff-aab5-f105d95c2f29.png)

## Created GameManager.cs to handle button input and toggling of rain
### GameManager.cs
```cs
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using DigitalRuby.RainMaker;

public class GameManager : MonoBehaviour
{
    //PUBLIC VARS
    public GameObject rainEffect;
    public Light directionalLight;
    public Button btnRainToggle;

    //PRIVATE VARS
    private bool _rain = false;

    //ROPERTIES
    public bool Rain{ 
        get{
            return Rain;
        }
        set{
            _rain = value;
        }
    }

    private void Update() {
        if(_rain){
            //finding the RainScript component and setting the RainIntensity to 1 to add the rain
            rainEffect.GetComponent<RainScript>().RainIntensity = 1;

            //reducing the light intensity to give the impression of rainy day
            directionalLight.intensity = 0.45f;
            btnRainToggle.GetComponentInChildren<TextMeshProUGUI>().text = "Rainy";
        }
        else{
            //finding the RainScript component and setting the RainIntensity to 0 to remove the rain
            rainEffect.GetComponent<RainScript>().RainIntensity = 0;

            //increasing the light intensity to give the impression of sunny day
            directionalLight.intensity = 1.5f;
            btnRainToggle.GetComponentInChildren<TextMeshProUGUI>().text = "Sunny";
        }
        Debug.Log(directionalLight.intensity);
    }

    public void OnClick_BtnRainToggle(){
        //flipping the valie of _rain
        _rain = !_rain;
    }

    public void OnTargetFound_ShowButton(){
        btnRainToggle.gameObject.SetActive(true);
        rainEffect.GetComponent<RainScript>().RainIntensity = 0;
    }
    
    public void OnTargetLost_HideButton(){
        btnRainToggle.gameObject.SetActive(false);
        rainEffect.GetComponent<RainScript>().RainIntensity = 0;
    }
}
```

## Added new objects to scene
![image](https://user-images.githubusercontent.com/84174550/173160209-f3c16446-4a61-4142-a150-311b58e91013.png)


### Notes:
- Rain effect barely shows when camera is active, hard to see, will look into it and try to rectify
- Sounds and Button function work fine

> Will continue to work on the issues

**Comment by R0TX** [comment]
# Fixed issue with the rain not showing up + Possible improvements to this feature

## Addressing invisible rain issue
### Main cause:
In GameManager.cs, setting the light intensity to < 1f caused the rain not to show due to the fact that the rain from the RainMaker asset6 uses the scene lighting to display the rain particles, therefore, setting the intensity too low causes the particles to not appear.
> Ie. The asset was working as intended but the particles did not show due to the light intensity being too low

### Changes to the code:
+1.0f to statements that adjust the light intensity

### GameManager.cs (Affected code):
```cs
    private void Update() {
        if(_rain){
            //finding the RainScript component and setting the RainIntensity to 1 to add the rain
            rainEffect.GetComponent<RainScript>().RainIntensity = 1;

            //reducing the light intensity to give the impression of rainy day
            directionalLight.intensity = 1.5f;
            btnRainToggle.GetComponentInChildren<TextMeshProUGUI>().text = "Rainy";
        }
        else{
            //finding the RainScript component and setting the RainIntensity to 0 to remove the rain
            rainEffect.GetComponent<RainScript>().RainIntensity = 0;

            //increasing the light intensity to give the impression of sunny day
            directionalLight.intensity = 2.5f;
            btnRainToggle.GetComponentInChildren<TextMeshProUGUI>().text = "Sunny";
        }
    }
```
Edits:
- Changed directionalLight.Intensity values to 1.5f and 2.5f for if and else blocks respectively

## Possible improvement to this feature:
- Use sun and rainy-cloud icons for the button instead of using a text button to give a more sleek and elegant feeling UI [^Button]
- Create a 3rd mode of the weather, stormy, which would include wind and (possibly) thunder sounds and heavier rain [^heavyRain]

Will look into sourcing, adding and implementing the aforementioned features in the coming commits

[^Button]: May be scrapped if satisfactory images cannot be found, unlikely but possible
[^heavyRain]: Due to the way that the RainMaker asset works, the current rain setting has to be lowered below 1f as 1 is the max setting of the rainIntensity of the rain prefab from the asset will experiment and test

**Comment by R0TX** [comment]
# Improvements + Minor Bug Fixes
Added improvements mentioned in previous issue

## Added 3rd mode of weather "Stormy" to the other 2 states
Minor change to the code to allow for multiple states; Code was changed to use Enums instead of just a simple boolean



### GameManager.cs:
```cs
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using DigitalRuby.RainMaker;

public class GameManager : MonoBehaviour
{
    //PUBLIC VARS
    public GameObject rainEffect;
    public Light directionalLight;
    public Button btnRainToggle;
    public Image btnRainToggleImage;

    //sprites
    public Sprite sunSprite;
    public Sprite rainSprite;
    public Sprite stormSprite;

    //PRIVATE VARS
    public enum RainMode{ 
        Sunny,
        Rain,
        Storm
    }
    private RainMode _rain = RainMode.Sunny;
    private int _rainValue = 0; //0 = Sunny, 1 = Rain, 2 = Storm

    //PROPERTIES
    public bool Rain{ 
        get{
            return Rain;
        }
    }

    private void Update() {
        if(_rain == RainMode.Storm){
            //STORM STATE
            //finding the RainScript component and setting the RainIntensity to 1 to have the maximum rain effect
            rainEffect.GetComponent<RainScript>().RainIntensity = 1f;

            //further reducing the light intensity to 1f to give the impression of heavy storms
            directionalLight.intensity = 0.8f;
            btnRainToggleImage.sprite = stormSprite;

            //enabling the wind sounds
            rainEffect.GetComponent<RainScript>().EnableWind = true;
        }
        else if(_rain == RainMode.Rain){
            //RAIN STATE
            //finding the RainScript component and setting the RainIntensity to 0.75 to add the rain
            rainEffect.GetComponent<RainScript>().RainIntensity = 0.75f;

            //reducing the light intensity to give the impression of rainy day
            directionalLight.intensity = 1.2f;
            btnRainToggleImage.sprite = rainSprite;

            //disabling wind sounds
            rainEffect.GetComponent<RainScript>().EnableWind = false;
        }
        else{
            //finding the RainScript component and setting the RainIntensity to 0 to remove the rain
            rainEffect.GetComponent<RainScript>().RainIntensity = 0;

            //increasing the light intensity to give the impression of sunny day
            directionalLight.intensity = 2f;
            btnRainToggleImage.sprite = sunSprite;

            //disabling wind sounds
            rainEffect.GetComponent<RainScript>().EnableWind = false;
        }
    }

    public void OnClick_btnRainToggle(){
        //cycling the values of _rain
        _rainValue += 1;

        if(_rainValue >= 3){
            //if _rainValue is >= number of items in RainMode, change the value to 0 (RainMode.Sunny)
            _rainValue = 0;
        }

        switch(_rainValue){
            case 0:
                //0 = Sunny mode
                _rain = RainMode.Sunny;
                break;
            case 1:
                //1 = Rain mode
                _rain = RainMode.Rain;
                break;
            case 2:
                //2 = Storm mode
                _rain = RainMode.Storm;
                break;
        }
    }

    public void OnTargetFound_ShowButton(){
        btnRainToggle.gameObject.SetActive(true);
        _rain = RainMode.Sunny;
        rainEffect.GetComponent<RainScript>().EnableWind = false;
    }
    
    public void OnTargetLost_HideButton(){
        btnRainToggle.gameObject.SetActive(false);
        _rain = RainMode.Sunny;
        rainEffect.GetComponent<RainScript>().EnableWind = false;
    }
}
```
Edits:
- Code now utilises enums for switching between states
   - _rainMode enum to keep track of current state
   - _rainValue to select current state dynamically
   - Changed Update(), OnTargetLost_HideButton() and OnTargetFound_ShowButton() to use _rain and set EnableWind for RainMaker asset
- Rain mode lightIntensity value now changed to 1.2f and rainIntensity value is now 0.75f to accommodate Storm mode (lightIntensity = 0.8, rainIntensity = 1f)
- GameManager.cs now changeds the button's image to the corresponding state sprite 

## Minor Bug Fixes
Fixed minor bugs pertaining to rain feature

### Fixed issue where rain did not stop working even after target was lost
_Issue was caused by the state not being reset to "RainMode.Sunny" after target was lost, Update handles removing rain after it is set to Sunny_

### Reduced overall lightIntensity for RainMode.Sunny to reduce overexposure effect (2.5f to 2f)
_Game objects look overexposed with the original values, ie they looked way too bright, thus lowering lightIntensity across the board reduces that effect_

**Comment by R0TX** [comment]
> All tasks and modifications are now complete, closing this issue and merging with main after (Last commit: b6ab06e6be0f1e6a9f938b298ca78adf53201251)

**Comment by R0TX** [comment]
# Improvements + Minor Bug Fixes
Added improvements mentioned in previous issue

## Added 3rd mode of weather "Stormy" to the other 2 states
Minor change to the code to allow for multiple states; Code was changed to use Enums instead of just a simple boolean



### GameManager.cs:
```cs
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using DigitalRuby.RainMaker;

public class GameManager : MonoBehaviour
{
    //PUBLIC VARS
    public GameObject rainEffect;
    public Light directionalLight;
    public Button btnRainToggle;
    public Image btnRainToggleImage;

    //sprites
    public Sprite sunSprite;
    public Sprite rainSprite;
    public Sprite stormSprite;

    //PRIVATE VARS
    public enum RainMode{ 
        Sunny,
        Rain,
        Storm
    }
    private RainMode _rain = RainMode.Sunny;
    private int _rainValue = 0; //0 = Sunny, 1 = Rain, 2 = Storm

    //PROPERTIES
    public bool Rain{ 
        get{
            return Rain;
        }
    }

    private void Update() {
        if(_rain == RainMode.Storm){
            //STORM STATE
            //finding the RainScript component and setting the RainIntensity to 1 to have the maximum rain effect
            rainEffect.GetComponent<RainScript>().RainIntensity = 1f;

            //further reducing the light intensity to 1f to give the impression of heavy storms
            directionalLight.intensity = 0.8f;
            btnRainToggleImage.sprite = stormSprite;

            //enabling the wind sounds
            rainEffect.GetComponent<RainScript>().EnableWind = true;
        }
        else if(_rain == RainMode.Rain){
            //RAIN STATE
            //finding the RainScript component and setting the RainIntensity to 0.75 to add the rain
            rainEffect.GetComponent<RainScript>().RainIntensity = 0.75f;

            //reducing the light intensity to give the impression of rainy day
            directionalLight.intensity = 1.2f;
            btnRainToggleImage.sprite = rainSprite;

            //disabling wind sounds
            rainEffect.GetComponent<RainScript>().EnableWind = false;
        }
        else{
            //finding the RainScript component and setting the RainIntensity to 0 to remove the rain
            rainEffect.GetComponent<RainScript>().RainIntensity = 0;

            //increasing the light intensity to give the impression of sunny day
            directionalLight.intensity = 2f;
            btnRainToggleImage.sprite = sunSprite;

            //disabling wind sounds
            rainEffect.GetComponent<RainScript>().EnableWind = false;
        }
    }

    public void OnClick_btnRainToggle(){
        //cycling the values of _rain
        _rainValue += 1;

        if(_rainValue >= 3){
            //if _rainValue is >= number of items in RainMode, change the value to 0 (RainMode.Sunny)
            _rainValue = 0;
        }

        switch(_rainValue){
            case 0:
                //0 = Sunny mode
                _rain = RainMode.Sunny;
                break;
            case 1:
                //1 = Rain mode
                _rain = RainMode.Rain;
                break;
            case 2:
                //2 = Storm mode
                _rain = RainMode.Storm;
                break;
        }
    }

    public void OnTargetFound_ShowButton(){
        btnRainToggle.gameObject.SetActive(true);
        _rain = RainMode.Sunny;
        rainEffect.GetComponent<RainScript>().EnableWind = false;
    }
    
    public void OnTargetLost_HideButton(){
        btnRainToggle.gameObject.SetActive(false);
        _rain = RainMode.Sunny;
        rainEffect.GetComponent<RainScript>().EnableWind = false;
    }
}
```
Edits:
- Code now utilises enums for switching between states
   - _rainMode enum to keep track of current state
   - _rainValue to select current state dynamically
   - Changed Update(), OnTargetLost_HideButton() and OnTargetFound_ShowButton() to use _rain and set EnableWind for RainMaker asset
- Rain mode lightIntensity value now changed to 1.2f and rainIntensity value is now 0.75f to accommodate Storm mode (lightIntensity = 0.8, rainIntensity = 1f)
- GameManager.cs now changeds the button's image to the corresponding state sprite 

## Minor Bug Fixes
Fixed minor bugs pertaining to rain feature

### Fixed issue where rain did not stop working even after target was lost
Issue was caused by the state not being reset to "RainMode.Sunny" after target was lost, Update handles removing rain after it is set to Sunny

### Reduced overall lightIntensity for RainMode.Sunny to reduce overexposure effect (2.5f to 2f)

**Comment by R0TX** [comment]
# Final feature showcase
https://user-images.githubusercontent.com/84174550/173445796-8dad00cb-25bb-4969-ade8-a3d87a392243.mp4

> Feature has been implemented, issue can now be closed, branch will be merged with main (Pull request: #3 )
